services:
  db:
    image: postgres:17
    container_name: db_app
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    command: -p ${DB_PORT}
    expose:
      - ${DB_PORT}

  redis:
    image: redis:7
    container_name: redis_app
    command: --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD} --notify-keyspace-events Ex
    expose:
      - ${REDIS_PORT}

  app:
    build:
      context: .
    container_name: fastapi_app
    command: [ "/fastapi_app/docker/app.sh" ]
    ports:
      - "9999:8000"
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: [ "/fastapi_app/docker/celery_worker.sh" ]
    depends_on:
      - app
      - redis

  celery_beat:
    build: .
    command: [ "/fastapi_app/docker/celery_beat.sh" ]
    depends_on:
      - app
      - redis