"""Added links table

Revision ID: 4edd0fa58f21
Revises: 
Create Date: 2025-03-30 23:15:52.554756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4edd0fa58f21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_expires_at'), 'links', ['expires_at'], unique=False)
    op.create_index(op.f('ix_links_original_url'), 'links', ['original_url'], unique=False)
    op.create_index(op.f('ix_links_short_url'), 'links', ['short_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_short_url'), table_name='links')
    op.drop_index(op.f('ix_links_original_url'), table_name='links')
    op.drop_index(op.f('ix_links_expires_at'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
